# OCTALUM-PULSE Helm Chart - ConfigMap Template
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Harery

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulse.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
data:
  OCTALUM-PULSE_LOG_LEVEL: {{ .Values.pulse.logLevel | quote }}
  TZ: {{ .Values.pulse.timezone | quote }}
