# OCTALUM-PULSE Kubernetes Namespace
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Harery

apiVersion: v1
kind: Namespace
metadata:
  name: pulse
  labels:
    name: pulse
    app.kubernetes.io/name: pulse
    app.kubernetes.io/component: system-maintenance
    app.kubernetes.io/part-of: pulse
    app.kubernetes.io/managed-by: kubectl
